version: "3.9"
services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_PASSWORD=password1
      - POSTGRES_USER=postgres
      - POSTGRES_DB=chat
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./db/chat/data:/var/lib/postgresql/data
    ports:
      - "5442:5432"
    restart: always
  app:
    image: chat
    container_name: chat
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/chat
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password1
    ports:
      - "9090:8080"
    depends_on:
      - db